// Package test holds integration tests that run against a local anvil node
// deployed via the testkit harness.
//
// Usage:
//
//	testkit/scripts/start-anvil.sh
//	ERC8301_ADDRESS=$(testkit/scripts/deploy.sh execution/ERC8301 DeployERC8301)
//	ERC8301_ADDRESS="$ERC8301_ADDRESS" go test -v ./go/test/ -run TestERC8301
//	testkit/scripts/stop-anvil.sh
//
// The signer key is read from testkit/.anvil-accounts.json (account #0,
// generated by start-anvil.sh) or from the ANVIL_KEY env var.
package test

import (
	"context"
	"crypto/ecdsa"
	"encoding/json"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/trustless-ai/agent-sdk/go/execution/erc8301"
)

func TestERC8301AgentWorkflow(t *testing.T) {
	addr := common.HexToAddress(os.Getenv("ERC8301_ADDRESS"))
	if addr == (common.Address{}) {
		t.Fatal("ERC8301_ADDRESS not set — deploy first via testkit/scripts/deploy.sh execution/ERC8301 DeployERC8301")
	}

	rpc, err := ethclient.Dial(anvilRPC)
	if err != nil {
		t.Fatalf("ethclient.Dial(%s): %v", anvilRPC, err)
	}
	defer rpc.Close()

	key := anvilSignerKey(t)
	signer := crypto.PubkeyToAddress(key.PublicKey)
	t.Logf("signer = %s", signer.Hex())

	client := erc8301.NewAgentWorkflowClient(rpc, addr, key)

	// ── run(): start a workflow run and capture the dispatched task ──────
	inputHash := crypto.Keccak256Hash([]byte("agent-1 input"))
	info, err := client.Run(context.Background(), inputHash, []byte("agent-1 input"), 2000000000)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	t.Logf("run() → runId=%s stage=%d taskHash=%s", info.WorkflowRunId.Hex(), info.Stage, info.TaskHash.Hex())
	if info.WorkflowRunId == (common.Hash{}) {
		t.Error("run() returned zero workflowRunId")
	}
	if info.Stage != 1 {
		t.Errorf("run() stage = %d, want 1 (mock dispatches the initial task at stage 1)", info.Stage)
	}

	// ── getAgentTask(): the stored struct is the recompute input ─────────
	task, proven, err := client.GetTask(context.Background(), info.TaskHash)
	if err != nil {
		t.Fatalf("GetTask(%s): %v", info.TaskHash.Hex(), err)
	}
	t.Logf("getAgentTask → stage=%d seq=%d inputHash=%s timestamp=%d expiresAt=%d proven=%v",
		task.Stage, task.TaskSeq, task.InputHash.Hex(), task.Timestamp, task.ExpiresAt, proven)
	if !proven {
		t.Error("initial task proven = false, want true (empty prevReplyHashes)")
	}
	if task.Stage != info.Stage {
		t.Errorf("task stage = %d, want %d", task.Stage, info.Stage)
	}
	if task.TaskSeq.Uint64() != 0 {
		t.Errorf("task taskSeq = %d, want 0 (per-run counter starts at 0)", task.TaskSeq)
	}
	if task.InputHash != inputHash {
		t.Errorf("task inputHash = %s, want %s", task.InputHash.Hex(), inputHash.Hex())
	}
	if task.WorkflowRunId != info.WorkflowRunId {
		t.Errorf("task workflowRunId = %s, want %s", task.WorkflowRunId.Hex(), info.WorkflowRunId.Hex())
	}

	// ── recompute-to-verify: taskHash from the stored fields matches ─────
	recomputedTask, err := erc8301.ComputeTaskHash(
		task.Stage, task.TaskSeq.Uint64(), task.InputHash,
		task.Timestamp.Uint64(), task.ExpiresAt.Uint64(),
		nil, // initial task has empty prevReplyHashes
		task.WorkflowRunId,
	)
	if err != nil {
		t.Fatalf("ComputeTaskHash: %v", err)
	}
	t.Logf("recomputed taskHash = %s", recomputedTask.Hex())
	if recomputedTask != info.TaskHash {
		t.Errorf("recomputed taskHash %s != NewAgentTask event taskHash %s", recomputedTask.Hex(), info.TaskHash.Hex())
	}

	// ── result(): run is still pending ───────────────────────────────────
	runResult, err := client.Result(context.Background(), info.WorkflowRunId)
	if err != nil {
		t.Fatalf("Result: %v", err)
	}
	if runResult.Status != erc8301.RunStatusPending {
		t.Errorf("result status = %d, want %d (Pending)", runResult.Status, erc8301.RunStatusPending)
	}

	// ── onAgentReply(): anchor a reply to the dispatched task ─────────────
	reply := erc8301.AgentReply{
		OutputHash:     crypto.Keccak256Hash([]byte("agent-1 output")),
		Output:         []byte("agent-1 output"),
		Timestamp:      big.NewInt(1700000000),
		Replier:        signer,
		PrevTaskHashes: []common.Hash{info.TaskHash},
		WorkflowRunId:  info.WorkflowRunId,
	}
	if _, err := client.OnAgentReply(context.Background(), reply); err != nil {
		t.Fatalf("OnAgentReply: %v", err)
	}

	// ── recompute-to-verify: replyHash anchors under the off-chain hash ──
	replyHash, err := erc8301.ComputeReplyHash(
		reply.OutputHash, reply.Timestamp.Uint64(), reply.Replier,
		packHashes(reply.PrevTaskHashes),
		reply.WorkflowRunId,
	)
	if err != nil {
		t.Fatalf("ComputeReplyHash: %v", err)
	}
	t.Logf("recomputed replyHash = %s", replyHash.Hex())

	storedReply, verifier, replyProven, digest, err := client.GetReply(context.Background(), replyHash)
	if err != nil {
		t.Fatalf("GetReply(%s): %v", replyHash.Hex(), err)
	}
	if storedReply.OutputHash != reply.OutputHash {
		t.Errorf("stored reply outputHash = %s, want %s", storedReply.OutputHash.Hex(), reply.OutputHash.Hex())
	}
	if storedReply.Replier != signer {
		t.Errorf("stored reply replier = %s, want %s", storedReply.Replier.Hex(), signer.Hex())
	}
	if replyProven {
		t.Error("reply proven = true before onAgentProve, want false")
	}
	if verifier != (common.Address{}) {
		t.Errorf("reply verifier = %s before prove, want zero address", verifier.Hex())
	}
	if digest != (common.Hash{}) {
		t.Errorf("reply verificationDigest = %s before prove, want zero", digest.Hex())
	}

	// ── onAgentProve(): mark the anchored reply proven ────────────────────
	proof := []byte("agent-1 proof")
	if _, err := client.OnAgentProve(context.Background(), []common.Hash{replyHash}, proof); err != nil {
		t.Fatalf("OnAgentProve: %v", err)
	}
	_, verifier, replyProven, digest, err = client.GetReply(context.Background(), replyHash)
	if err != nil {
		t.Fatalf("GetReply after prove: %v", err)
	}
	if !replyProven {
		t.Error("reply proven = false after onAgentProve, want true")
	}
	if verifier != signer {
		t.Errorf("reply verifier = %s, want signer %s", verifier.Hex(), signer.Hex())
	}
	if digest != crypto.Keccak256Hash(proof) {
		t.Errorf("reply verificationDigest = %s, want keccak256(proof) %s", digest.Hex(), crypto.Keccak256Hash(proof).Hex())
	}

	// ── unknown hashes must error (the mock reverts) ──────────────────────
	if _, _, err := client.GetTask(context.Background(), common.Hash{}); err == nil {
		t.Error("GetTask(zero) returned nil error, want revert for unknown taskHash")
	}
	if _, _, _, _, err := client.GetReply(context.Background(), common.Hash{}); err == nil {
		t.Error("GetReply(zero) returned nil error, want revert for unknown replyHash")
	}
}

// packHashes concatenates the 32-byte hashes — abi.encodePacked of the
// prev-hash list.
func packHashes(hashes []common.Hash) []byte {
	var packed []byte
	for _, h := range hashes {
		packed = append(packed, h.Bytes()...)
	}
	return packed
}

// anvilSignerKey returns the testkit anvil account #0 private key, read from
// the ANVIL_KEY env var or from testkit/.anvil-accounts.json (generated by
// testkit/scripts/start-anvil.sh).
func anvilSignerKey(t *testing.T) *ecdsa.PrivateKey {
	t.Helper()
	hexKey := os.Getenv("ANVIL_KEY")
	if hexKey == "" {
		data, err := os.ReadFile(anvilAccountsPath(t))
		if err != nil {
			t.Fatalf("ANVIL_KEY not set and .anvil-accounts.json unreadable: %v — start anvil first via testkit/scripts/start-anvil.sh", err)
		}
		var accts struct {
			Accounts []struct {
				PrivateKey string `json:"privateKey"`
			} `json:"accounts"`
		}
		if err := json.Unmarshal(data, &accts); err != nil {
			t.Fatalf("parse .anvil-accounts.json: %v", err)
		}
		if len(accts.Accounts) == 0 || accts.Accounts[0].PrivateKey == "" {
			t.Fatalf(".anvil-accounts.json has no account[0].privateKey")
		}
		hexKey = accts.Accounts[0].PrivateKey
	}
	hexKey = strings.TrimPrefix(hexKey, "0x")
	key, err := crypto.HexToECDSA(hexKey)
	if err != nil {
		t.Fatalf("parse signer key: %v", err)
	}
	return key
}

// anvilAccountsPath locates testkit/.anvil-accounts.json relative to the test
// package's working directory (go test runs with cwd = package dir).
func anvilAccountsPath(t *testing.T) string {
	t.Helper()
	for _, rel := range []string{"../../testkit/.anvil-accounts.json", "testkit/.anvil-accounts.json"} {
		if abs, err := filepath.Abs(rel); err == nil {
			if _, err := os.Stat(abs); err == nil {
				return abs
			}
		}
	}
	return "../../testkit/.anvil-accounts.json"
}
