import { verifyProofLocal, type LocalProofResult } from 'invinoveritas-verify'
import type { ReviewGateConfig, ReviewOptions, ReviewResponse } from './types.js'

const DEFAULT_BASE_URL = 'https://api.babyblueviper.com'

/**
 * A pre-action judgment gate: call `review()` with a proposed action before
 * an agent executes it, get back a verdict (approve / reject /
 * approve_with_concerns) plus a signed proof you verify yourself — never a
 * bare "trust me" boolean.
 *
 * This is deliberately NOT tied to an agent-ercs interface. invinoveritas's
 * `/review` is a plain off-chain HTTP judgment service, not an on-chain
 * contract, so it doesn't fit the `<category>/<ERCXXXX>` generation pattern
 * the rest of this SDK follows — see README.md in this directory for why
 * it's hand-written rather than generated by `/add-erc`.
 */
export class ReviewGateClient {
  private readonly apiKey: string
  private readonly baseUrl: string

  constructor(config: ReviewGateConfig) {
    this.apiKey = config.apiKey
    this.baseUrl = (config.baseUrl ?? DEFAULT_BASE_URL).replace(/\/$/, '')
  }

  /**
   * Get a verdict on a proposed action before it executes.
   *
   * @param artifact - The proposed action, as text: a shell command, a code
   *   diff, an order description — whatever the agent is about to do.
   * @param options - Optional artifact type, extra context, and whether to
   *   request a signed proof (default true).
   */
  async review(artifact: string, options: ReviewOptions = {}): Promise<ReviewResponse> {
    const body: Record<string, unknown> = {
      artifact,
      sign: options.sign ?? true,
    }
    if (options.artifactType) body.artifact_type = options.artifactType
    if (options.context) body.context = options.context

    const res = await fetch(`${this.baseUrl}/review`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify(body),
    })

    if (!res.ok) {
      const detail = await res.text().catch(() => '')
      throw new Error(`invinoveritas /review returned ${res.status}: ${detail.slice(0, 500)}`)
    }

    return (await res.json()) as ReviewResponse
  }

  /**
   * Independently verify a review response's signed proof — a pure,
   * offline recompute via `invinoveritas-verify` (BIP-340 Schnorr over the
   * NIP-01 event id, checked against invinoveritas's published pubkey).
   * No network call, no trust in this client or in invinoveritas's own
   * infrastructure: this is the same check anyone else can run against the
   * bytes alone.
   *
   * @param response - A `ReviewResponse` from `review()` that was called
   *   with `sign: true` (the default).
   * @throws if the response has no `proof.event` to verify (it was called
   *   with `sign: false`).
   */
  verifyLocal(response: ReviewResponse): LocalProofResult {
    if (!response.proof?.event) {
      throw new Error(
        'No signed event on this response — call review() with sign:true (the default) to get a verifiable proof.',
      )
    }
    return verifyProofLocal(response.proof.event as unknown as Record<string, unknown>)
  }
}
