CONSULT_ESCROW_ABI = [
    {
        "type": "function",
        "name": "open",
        "stateMutability": "payable",
        "inputs": [
            {"name": "jobId", "type": "bytes32"},
            {"name": "provider", "type": "address"},
            {"name": "attestor", "type": "address"},
            {"name": "deadline", "type": "uint256"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "release",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "jobId", "type": "bytes32"},
            {"name": "resultHash", "type": "bytes32"},
            {"name": "signature", "type": "bytes"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "refund",
        "stateMutability": "nonpayable",
        "inputs": [{"name": "jobId", "type": "bytes32"}],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "jobs",
        "stateMutability": "view",
        "inputs": [{"name": "jobId", "type": "bytes32"}],
        "outputs": [
            {"name": "consumer", "type": "address"},
            {"name": "provider", "type": "address"},
            {"name": "attestor", "type": "address"},
            {"name": "amount", "type": "uint256"},
            {"name": "deadline", "type": "uint256"},
            {"name": "status", "type": "uint8"},
        ],
    },
    {
        "type": "event",
        "name": "Opened",
        "anonymous": False,
        "inputs": [
            {"name": "jobId", "type": "bytes32", "indexed": True},
            {"name": "consumer", "type": "address", "indexed": True},
            {"name": "provider", "type": "address", "indexed": True},
            {"name": "attestor", "type": "address", "indexed": False},
            {"name": "amount", "type": "uint256", "indexed": False},
            {"name": "deadline", "type": "uint256", "indexed": False},
        ],
    },
    {
        "type": "event",
        "name": "Released",
        "anonymous": False,
        "inputs": [
            {"name": "jobId", "type": "bytes32", "indexed": True},
            {"name": "resultHash", "type": "bytes32", "indexed": False},
            {"name": "commitmentHash", "type": "bytes32", "indexed": False},
            {"name": "provider", "type": "address", "indexed": False},
            {"name": "amount", "type": "uint256", "indexed": False},
        ],
    },
    {
        "type": "event",
        "name": "Refunded",
        "anonymous": False,
        "inputs": [
            {"name": "jobId", "type": "bytes32", "indexed": True},
            {"name": "consumer", "type": "address", "indexed": False},
            {"name": "amount", "type": "uint256", "indexed": False},
        ],
    },
]
